// Photo par modèle (Wikimedia Commons, CC BY-SA). Généré automatiquement.
export const MODEL_IMAGES = {
  "iPhone 16 Pro Max": "./img/models/by-model/iphone-16-pro-max.png",
  "iPhone 16 Pro": "./img/models/by-model/iphone-16-pro.jpg",
  "iPhone 16": "./img/models/by-model/iphone-16.jpg",
  "iPhone 15 Pro Max": "./img/models/by-model/iphone-15-pro-max.jpg",
  "iPhone 15": "./img/models/by-model/iphone-15.jpg",
  "iPhone 14 Pro Max": "./img/models/by-model/iphone-14-pro-max.jpg",
  "iPhone 14": "./img/models/by-model/iphone-14.jpg",
  "iPhone 13 Pro Max": "./img/models/by-model/iphone-13-pro-max.jpg",
  "iPhone 13": "./img/models/by-model/iphone-13.jpg",
  "iPhone 12 Pro Max": "./img/models/by-model/iphone-12-pro-max.png",
  "iPhone 12": "./img/models/by-model/iphone-12.png",
  "iPhone 11 Pro Max": "./img/models/by-model/iphone-11-pro-max.jpg",
  "iPhone 11": "./img/models/by-model/iphone-11.jpg",
  "iPhone XR": "./img/models/by-model/iphone-xr.jpg",
  "iPhone X": "./img/models/by-model/iphone-x.jpg",
  "iPhone 8 / SE 2020": "./img/models/by-model/iphone-8-se-2020.jpg",
  "iPhone 7": "./img/models/by-model/iphone-7.jpg",
  "Galaxy S24 Ultra": "./img/models/by-model/galaxy-s24-ultra.jpg",
  "Galaxy S24": "./img/models/by-model/galaxy-s24.jpg",
  "Galaxy S23": "./img/models/by-model/galaxy-s23.png",
  "Galaxy S22": "./img/models/by-model/galaxy-s22.png",
  "Galaxy S21": "./img/models/by-model/galaxy-s21.png",
  "Galaxy A54": "./img/models/by-model/galaxy-a54.jpg",
  "Galaxy A53": "./img/models/by-model/galaxy-a53.png",
  "Galaxy A34": "./img/models/by-model/galaxy-a34.png",
  "Galaxy A14": "./img/models/by-model/galaxy-a14.jpg",
  "Xiaomi 13": "./img/models/by-model/xiaomi-13.jpg",
  "Xiaomi 12": "./img/models/by-model/xiaomi-12.jpg",
  "Redmi Note 13": "./img/models/by-model/redmi-note-13.jpg",
  "Redmi Note 12": "./img/models/by-model/redmi-note-12.jpg",
  "Redmi 12": "./img/models/by-model/redmi-12.jpg",
  "P40 Pro": "./img/models/by-model/p40-pro.jpg",
  "P30 Pro": "./img/models/by-model/p30-pro.jpg",
  "P30 Lite": "./img/models/by-model/p30-lite.jpg",
  "Mate 20 Pro": "./img/models/by-model/mate-20-pro.jpg",
  "Pixel 8 Pro": "./img/models/by-model/pixel-8-pro.jpg",
  "Pixel 8": "./img/models/by-model/pixel-8.jpg",
  "Pixel 7": "./img/models/by-model/pixel-7.jpg",
  "Pixel 6": "./img/models/by-model/pixel-6.jpg",
  "iPad Pro 12.9\"": "./img/models/by-model/ipad-pro-12-9.jpg",
  "iPad Pro 11\"": "./img/models/by-model/ipad-pro-11.jpg",
  "iPad Air": "./img/models/by-model/ipad-air.png",
  "iPad 10 / 9": "./img/models/by-model/ipad-10-9.jpg",
  "iPad mini": "./img/models/by-model/ipad-mini.png"
};
